#!/bin/bash

source /etc/update-motd.d/colors.txt

echo -e " ${TITLE_COLOR}Users logged in.....:${NC} ${TEXT_COLOR}$(w -h | awk '{ printf "%s ", $1; }') $(top -bn1 | awk 'BEGIN { FS=",  "; }
                $2~/user/ { print " (" $2 " total)"; }
                $3~/user/ { print " (" $3 " total)"; }')"
