#!/bin/bash

source /etc/update-motd.d/colors.txt

echo -e " ${TITLE_COLOR}Memory..............:${DEFAULT_COLOR} ${NC}Used: ${TEXT_COLOR}$(free -m | grep Mem: | xargs | cut -f3 -d' ')${DEFAULT_COLOR} ${NC}MB | ${NC}Free: ${TEXT_COLOR}$(free -m | grep Mem: | xargs | cut -f7 -d' ')${DEFAULT_COLOR} ${NC}MB | ${NC}Total: ${TEXT_COLOR}$(free -m | grep Mem: | xargs | cut -f2 -d' ')${DEFAULT_COLOR} ${NC}MB"
