---
- name: Edit journald.conf
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - { regexp: "^#?Storage", line: Storage=volatile }
    - { regexp: "^#?ForwardToSyslog", line: ForwardToSyslog=no }
    - { regexp: "^#?SystemMaxUse", line: SystemMaxUse=100M }
  notify: Restart systemd-journald
  vars:
    ansible_remote_tmp: /tmp # Prevent warnings for auto-created tmp dir

# A succesful vacuum impacts log size, report it as a change
# If the grep matches, it means at least one line had something else than 'freed 0B', i.e. actual values
# Only in that case, the returncode is 0.
# If returncode !=0, it simply means no vacuuming took place, so do not consider that an error.
- name: Vacuum journalctl to a maximum of 10MB
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      journalctl --vacuum-size=10M 2>&1 | grep -v 'freed 0B'
  register: vacuumresult
  changed_when: vacuumresult.rc == 0
  failed_when: false
