---
- name: Set default locale to en_US.UTF-8
  ansible.builtin.debconf:
    name: locales
    question: locales/default_environment_locale
    value: en_US.UTF-8
    vtype: select
  notify: Reconfigure locales

- name: Generate required locales
  ansible.builtin.debconf:
    name: locales
    question: locales/locales_to_be_generated
    value: en_US.UTF-8 UTF-8, nl_NL.UTF-8 UTF-8, en_GB.UTF-8 UTF-8
    vtype: multiselect
  notify: Reconfigure locales
