---
- name: Ensure that unprivileged user is present
  ansible.builtin.user:
    name: "{{ interactive_user }}"
    shell: /bin/bash
    home: "{{ interactive_home }}"
    password: "{{ interactive_password }}"
    groups: sudo
    create_home: true
    skeleton: /etc/skel
    append: true

# Andre February 2026: The SSH keys should be batch-added
# so I am querying all public keys containing 'yubi' and batch adding them
# private_repo is set in group_vars/all.yml
- name: Check the primary key for the unprivileged user
  ansible.posix.authorized_key:
    user: "{{ interactive_user }}"
    key: "{% for key in query('fileglob', private_repo ~ '/ssh-keys/' ~ interactive_user ~ '/' ~ interactive_user ~ '-yubi-*.pub') %}{{ lookup('file', key) ~ '\n'}}{% endfor %}" # noqa: yaml[line-length]
    state: present
    exclusive: false
  register: setkey

- name: Re-set the keys as exclusive, if we found that (one of) the keys was/were not present yet # noqa: no-handler
  when: setkey.changed
  ansible.posix.authorized_key:
    user: "{{ interactive_user }}"
    key: "{% for key in query('fileglob', private_repo ~ '/ssh-keys/' ~ interactive_user ~ '/' ~ interactive_user ~ '-yubi-*.pub') %}{{ lookup('file', key) ~ '\n'}}{% endfor %}" # noqa: yaml[line-length]
    state: present
    exclusive: true

- name: Install required package to become unprivileged users
  ansible.builtin.apt:
    name: acl
    state: present

- name: Remove the entire authorized_keys file for the ansible user, as this was for bootstrapping only
  ansible.builtin.file:
    path: "/home/{{ ansible_user | default('ansible') }}/.ssh/authorized_keys"
    state: absent
  become: true
  become_user: "{{ ansible_user | default('ansible') }}"
  when: ansible_user is defined
